// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20240704164138_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Base", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.OperationPhase", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationId", "PhaseId");

                    b.HasIndex("PhaseId");

                    b.ToTable("OperationPhase");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.ProcedureOperation", b =>
                {
                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureId", "OperationId");

                    b.HasIndex("OperationId");

                    b.ToTable("ProcedureOperation");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Execution", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base");

                    b.Property<string>("UnitCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitProcedureId")
                        .HasColumnType("TEXT");

                    b.HasIndex("UnitProcedureId");

                    b.ToTable("Operaciones", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base");

                    b.Property<Guid?>("OperationsId")
                        .HasColumnType("TEXT");

                    b.HasIndex("OperationsId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base");

                    b.Property<string>("UnitCode")
                        .HasColumnType("TEXT");

                    b.ToTable("Procedimientos", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.OperationExecution", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperCode")
                        .HasColumnType("TEXT");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationExecution", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.PhaseExecution", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperCode")
                        .HasColumnType("TEXT");

                    b.HasIndex("PhaseId");

                    b.ToTable("PhaseExecution", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.UnitExecution", b =>
                {
                    b.HasBaseType("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitExecution", (string)null);
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.OperationPhase", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", "Operation")
                        .WithMany("OperationPhase")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", "Phase")
                        .WithMany("OperationsPhase")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.ProcedureOperation", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", "Operation")
                        .WithMany("ProcedureOperation")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", "UnitProcedure")
                        .WithMany("ProcedureOperation")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("UnitProcedure");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", null)
                        .WithMany("Operations")
                        .HasForeignKey("UnitProcedureId");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", null)
                        .WithMany("phases")
                        .HasForeignKey("OperationsId");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Base", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.OperationExecution", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.OperationExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.PhaseExecution", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.PhaseExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.UnitExecution", b =>
                {
                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Utilities.UnitExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Operations", b =>
                {
                    b.Navigation("OperationPhase");

                    b.Navigation("ProcedureOperation");

                    b.Navigation("phases");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.Phases", b =>
                {
                    b.Navigation("OperationsPhase");
                });

            modelBuilder.Entity("Sistema_de_seguimiento_a_ejecuciones_de_procedimientos.Domain.Entities.UnitProcedure", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("ProcedureOperation");
                });
#pragma warning restore 612, 618
        }
    }
}
