// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20240705010318_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            modelBuilder.Entity("Domain.Domain.Entities.ProcedureControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcedureControl", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Utilities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Execution", (string)null);
                });

            modelBuilder.Entity("OperationsPhases", b =>
                {
                    b.Property<Guid>("PhasesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("operationsId")
                        .HasColumnType("TEXT");

                    b.HasKey("PhasesId", "operationsId");

                    b.HasIndex("operationsId");

                    b.ToTable("OperationsPhases");
                });

            modelBuilder.Entity("OperationsUnitProcedure", b =>
                {
                    b.Property<Guid>("OperationsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitProceduresId")
                        .HasColumnType("TEXT");

                    b.HasKey("OperationsId", "UnitProceduresId");

                    b.HasIndex("UnitProceduresId");

                    b.ToTable("OperationsUnitProcedure");
                });

            modelBuilder.Entity("Domain.Domain.Entities.Operations", b =>
                {
                    b.HasBaseType("Domain.Domain.Entities.ProcedureControl");

                    b.Property<string>("UnitCode")
                        .HasColumnType("TEXT");

                    b.ToTable("Operaciones", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Entities.Phases", b =>
                {
                    b.HasBaseType("Domain.Domain.Entities.ProcedureControl");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Entities.UnitProcedure", b =>
                {
                    b.HasBaseType("Domain.Domain.Entities.ProcedureControl");

                    b.Property<string>("UnitCode")
                        .HasColumnType("TEXT");

                    b.ToTable("Procedimientos", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Utilities.OperationExecution", b =>
                {
                    b.HasBaseType("Domain.Domain.Utilities.Execution");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperCode")
                        .HasColumnType("TEXT");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationExecution", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Utilities.PhaseExecution", b =>
                {
                    b.HasBaseType("Domain.Domain.Utilities.Execution");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperCode")
                        .HasColumnType("TEXT");

                    b.HasIndex("PhaseId");

                    b.ToTable("PhaseExecution", (string)null);
                });

            modelBuilder.Entity("Domain.Domain.Utilities.UnitExecution", b =>
                {
                    b.HasBaseType("Domain.Domain.Utilities.Execution");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitExecution", (string)null);
                });

            modelBuilder.Entity("OperationsPhases", b =>
                {
                    b.HasOne("Domain.Domain.Entities.Phases", null)
                        .WithMany()
                        .HasForeignKey("PhasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Domain.Entities.Operations", null)
                        .WithMany()
                        .HasForeignKey("operationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OperationsUnitProcedure", b =>
                {
                    b.HasOne("Domain.Domain.Entities.Operations", null)
                        .WithMany()
                        .HasForeignKey("OperationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Domain.Entities.UnitProcedure", null)
                        .WithMany()
                        .HasForeignKey("UnitProceduresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Domain.Entities.Operations", b =>
                {
                    b.HasOne("Domain.Domain.Entities.ProcedureControl", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Entities.Operations", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Domain.Entities.Phases", b =>
                {
                    b.HasOne("Domain.Domain.Entities.ProcedureControl", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Entities.Phases", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Domain.Entities.UnitProcedure", b =>
                {
                    b.HasOne("Domain.Domain.Entities.ProcedureControl", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Entities.UnitProcedure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Domain.Utilities.OperationExecution", b =>
                {
                    b.HasOne("Domain.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Utilities.OperationExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Domain.Entities.Operations", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Domain.Domain.Utilities.PhaseExecution", b =>
                {
                    b.HasOne("Domain.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Utilities.PhaseExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Domain.Entities.Phases", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("Domain.Domain.Utilities.UnitExecution", b =>
                {
                    b.HasOne("Domain.Domain.Utilities.Execution", null)
                        .WithOne()
                        .HasForeignKey("Domain.Domain.Utilities.UnitExecution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Domain.Entities.UnitProcedure", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
